stopwords_pt_br = {
              '([^0-9a-zÀ-ÿ]|^|\s+)(de|das?|dos?|nas?|nos?)+([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(as?|os?|e|é|às?|aos?)+([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(pois)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(ali[á|a]s|mai?s|menos|demais)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(porqu[ê|e]s?|por qu[ê|e]s?|pq|qual|quais)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(qu[ê|e]s?|q)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(geralmente|claramente|normalmente|provavelmente|necessariamente|freq[u|ü]entemente)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(bem|mal|v[á|a]ri[o|a]s|desde|cada)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(bastante|quando|assim|muit[o|a]s?|tudo|tod[o|a]s)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(atrav[é|e]s|durante|onde|perante|diante|atr[á|a]s|detr[á|a]s|frente|diante|aqui|ali)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(oi)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(em)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(ai|aí|ainda)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(para|pras?)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(como?)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(alguma?s?|alguns)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(n?uma?s?|n?uns)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(se)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(por)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(el[e|a]s)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)([s|t]uas?)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(ou)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(ent[ã|a]o|t[ã|a]o)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(j[á|a])([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(eu|tu|eles|elas?|n[ó|o]s|v[ó|o]s)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(tamb[é|e]m)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(pel[o|a]s?)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(at[é|e])([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(n?isso|n?isto|n?estes?|n?estas?|n?esses?|n?essas?)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(entre|entretanto|tanto|tanta)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(depois|ap[ó|o]s)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(sem)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(mesm[o|a]s?)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(meus?|teus?|seus?|nossos?|vossos?)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(minhas?|tuas?|suas?|nossas?|vossas?)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(quem?)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(segundo)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(mim|ti)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(me|te|l[a|o]s?|lhes?)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(nem)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(qual|qualquer|quaisquer)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(voc[ê|e]s?|vcs?)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(minhas)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(deles?|delas?)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)([a|à]queles?|[a|à]quelas?|[a|à]quilo)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(tô|to)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(tá|ta)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(neles?|nelas?)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(sobre|acima|antes|novamente|contra|quase)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(sozinh[o|a]s?|s[ó|o]|al[é|e]m|d?[i|e]ss[o|a|e]s?|apesar)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(entre|outr[a|o]s?|amb[o|a]s)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              # verbo ser
              '([^0-9a-zÀ-ÿ]|^|\s+)(sou|[é|e]s?|somos|sois|s[ã|a]o)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(fui|fostes?|foi|fomos|foram)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(eras?|[é|e]ramos?|[é|e]reis|eram)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(serei|ser[á|a]s?|seremos|sereis|ser[ã|a]o)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(serias?|ser[í|i]amos|ser[í|i]eis|seriam)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(sejas?|sejamos|sejais|sejam)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(fosses?|f[ô|o]ssemos|f[ô|o]sseis|fossem)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(for|fores|formos|fordes|forem)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(ser|seres|sermos|serdes|serem|sendo|sido)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              # verbo estar
              '([^0-9a-zÀ-ÿ]|^|\s+)(estou|est[á|a]s?|estamos|estais|est[ã|a]o)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(estive|estivestes?|esteve|estivemos|estiveram)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(estiveras?|estiv[é|e]ramos|estiv[é|e]reis)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(estavas?|est[á|a]vamos|est[á|a]veis|estavam)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(estarei|estar[á|a]s?|estaremos|estareis|estar[ã|a]o)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(estarias?|estar[í|i]amos|estar[í|i]eis|estariam)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(estejas?|estejamos|estejais|estejam)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(estivesses?|estiv[é|e]ssemos|estiv[é|e]sseis|estivessem)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(estiver|estiveres|estivermos|estiverdes|estiverem)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(estar|estares|estarmos|estardes|estarem|estando|estado)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              # verbo ter
              '([^0-9a-zÀ-ÿ]|^|\s+)(tenho|tens|tem|temos|tendes|t[ê|e]m)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(tinhas?|t[í|i]nhamos|t[í|i]nheis|tinham)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(tive|tivestes?|teve|tivemos|tiveram)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(terei|ter[á|a]s?|teremos|tereis|ter[ã|a]o)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(tiveras?|tiv[é|e]ramos|tiv[é|e]reis)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(terias?|ter[í|i]amos|ter[í|i]eis|teriam)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(tenhas?|tenhamos|tenhais|tenham)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(tivesses?|tiv[é|e]ssemos|tiv[é|e]sseis|tivessem)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(tiver|tiveres|tivemos|tiverdes|tiverem)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(ter|teres|termos|terdes|terem|tendo|tido)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              # verbo ir
              '([^0-9a-zÀ-ÿ]|^|\s+)(vou|vais?|vamos|ides|v[ã|a]o)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(ias?|[í|i]amos|[í|i]eis|iam)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(fui|fostes?|foi|fomos|foram)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(foras?|f[ô|o]ramos|f[ô|o]reis)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(irei|ir[á|a]s?|iremos|ireis|ir[ã|a]o)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(irias?|ir[í|i]amos|ir[í|i]eis|iriam)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(v[á|a]s?|vamos|vades)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(ir|ires|irmos|irdes|irem|indo|ido)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              # verbo haver
              '([^0-9a-zÀ-ÿ]|^|\s+)(hei|h[á|a]s?|havemos|haveis|h[ã|a]o)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(havias?|hav[í|i]amos|hav[í|i]eis|haviam)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(houve|houvestes?|houve|houvemos|houveram)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(haverei|haver[á|a]s?|haveremos|havereis|haver[ã|a]o)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(houveras?|houv[é|e]ramos|houv[é|e]reis)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(haverias?|haver[í|i]amos|haver[í|i]eis|haveriam)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(hajas?|hajamos|hajais|havei|hajam)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(houvesses?|houv[é|e]ssemos|houv[é|e]sseis|houvessem)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(houver|houveres|houvemos|houverdes|houverem)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
              '([^0-9a-zÀ-ÿ]|^|\s+)(haver|haveres|havermos|haverdes|haverem|havendo|havido)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3'
}




stopwords_en = {
    '([^0-9a-zÀ-ÿ]|^|\s+)(the|an?|and|with|but|to|of|on|for|int?o?)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
    '([^0-9a-zÀ-ÿ]|^|\s+)(me?y?)(self)?([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\4',
    '([^0-9a-zÀ-ÿ]|^|\s+)(we)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
    '([^0-9a-zÀ-ÿ]|^|\s+)(ours?)(self|selves)?([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\4',
    '([^0-9a-zÀ-ÿ]|^|\s+)(your?)(self|selves)?([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\4',
    '([^0-9a-zÀ-ÿ]|^|\s+)(s?he)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
    '([^0-9a-zÀ-ÿ]|^|\s+)(hers?)(self)?([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\4',
    '([^0-9a-zÀ-ÿ]|^|\s+)(his?m?)(self)?([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\4',
    '([^0-9a-zÀ-ÿ]|^|\s+)(it?s?)(self)?([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\4',
    '([^0-9a-zÀ-ÿ]|^|\s+)(them?y?)(self|selves)?([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\4',
    '([^0-9a-zÀ-ÿ]|^|\s+)(theirs?)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
    '([^0-9a-zÀ-ÿ]|^|\s+)(what|which|who|when|this|that|these|those)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
    '([^0-9a-zÀ-ÿ]|^|\s+)(am|is|are|was|were|be|been|being|have|has|had|having)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
    '([^0-9a-zÀ-ÿ]|^|\s+)(do|does|did|doing)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
    '([^0-9a-zÀ-ÿ]|^|\s+)(if|or|because|as|until|while|at|by|about|against|between)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
    '([^0-9a-zÀ-ÿ]|^|\s+)(through|during|before|after|above|below|at|by|about|against|between)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
    '([^0-9a-zÀ-ÿ]|^|\s+)(from|up|down|out|off|over|under|again|further|then|once)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
    '([^0-9a-zÀ-ÿ]|^|\s+)(t?w?here|why|how|all|any|both|each|few|more|most|other)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
    '([^0-9a-zÀ-ÿ]|^|\s+)(some|such|nor|only|own|same|so|than|too|very|s|t|can|will|just|also|don|should|would|could|now)([^0-9a-zÀ-ÿ]|\s+|$)':'\\1 \\3',
}